language: python
python:
  - "3.5.2"
  - "3.6.1"
install:
  - pip install -r requirements.txt
script:
  - python -m compileall ./fenicalappubot.py
  - python -m compileall ./cogs
  - python ./fenicalappubot.py --test-run
cache: pip
notifications:
  email: false
dist: xenial
os: linux
